export const unitsData = () => [
    {
        id: "1",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "2",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "3",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "4",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "5",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "6",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "7",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "8",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "9",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "10",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "11",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "12",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "13",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "14",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "15",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "16",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "17",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "18",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "19",
        name: "ENSET",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "FlexGrid",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Marko",
        address: "Kraigherjeva ulica 2",
        city: "Lenart v Slovenskih Goricah",
        zipCode: "2230",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "20",
        name: "ELMA TT",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "EKO-D",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Jože",
        address: "Predstruge 29",
        city: "Videm-Dobrepolj",
        zipCode: "1312",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
    {
        id: "21",
        name: "Bitnje 137",
        type: "Unit",
        function: "Resource Provider",
        energySupplier: "Gen-i",
        marketParticipant: "Reduxi GmbH",
        aggregator: "Sunlumo",
        offeredServices: ["Flex", "Energy Community"],
        owner: "Franci",
        address: "Zgornje Bitnje 137",
        city: "Kranj",
        zipCode: "4000",
        country: "Slovenia",
        coordinates: { lat: 53.4808, lng: -2.2426 },
        grid: { a: "3.500 MW / 3.500 MW", b: "100 A / 100 A" },
        pv: true,
        battery: true,
        hvac: true,
        evse: true,
        flexUpMw: 2.5,
        flexDownMw: 1.8,
    },
];
